//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanilla.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administracion
    {
        public Administracion()
        {
            this.Radicado = new HashSet<Radicado>();
        }
    
        public long CodAdmon { get; set; }
        public string NomAdmon { get; set; }
        public string ApeAdmon { get; set; }
        public string CargoAdmon { get; set; }
        public string AreaAdmon { get; set; }
        public Nullable<long> CodDespacho { get; set; }
        public Nullable<long> CodProceso { get; set; }
    
        public virtual Despacho Despacho { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual ICollection<Radicado> Radicado { get; set; }
    }
}
