//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanilla.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radicado
    {
        public long CodRadicado { get; set; }
        public Nullable<long> CodTercero { get; set; }
        public Nullable<long> CodAdmon { get; set; }
        public string Fecha_Radicado { get; set; }
        public string DescRadicado { get; set; }
        public Nullable<long> CodUsuario { get; set; }
    
        public virtual Administracion Administracion { get; set; }
        public virtual Terceros Terceros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
