//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanilla.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terceros
    {
        public Terceros()
        {
            this.Radicado = new HashSet<Radicado>();
        }
    
        public long CodTercero { get; set; }
        public string TelTercero { get; set; }
        public string EmailTercero { get; set; }
        public string DescTercero { get; set; }
    
        public virtual ICollection<Radicado> Radicado { get; set; }
    }
}
