//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanilla.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Radicado = new HashSet<Radicado>();
        }
    
        public long CodUsuario { get; set; }
        public string NomUsuario { get; set; }
        public string ApeUsuario { get; set; }
        public string CargoUsuario { get; set; }
    
        public virtual ICollection<Radicado> Radicado { get; set; }
    }
}
