//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDatos.Web.wsServicios {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsServicios.ConsultaRadicadoWsSoap")]
    public interface ConsultaRadicadoWsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AutenticacionUsuarioRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticacionUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse AutenticacionUsuario(WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticacionUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse> AutenticacionUsuarioAsync(WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje wsConsultaRadicadoRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaRadicado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse wsConsultaRadicado(WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaRadicado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse> wsConsultaRadicadoAsync(WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsSeguridad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stTokenField;
        
        private string autenticacionTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stToken {
            get {
                return this.stTokenField;
            }
            set {
                this.stTokenField = value;
                this.RaisePropertyChanged("stToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AutenticacionToken {
            get {
                return this.autenticacionTokenField;
            }
            set {
                this.autenticacionTokenField = value;
                this.RaisePropertyChanged("AutenticacionToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad;
        
        public AutenticacionUsuarioRequest() {
        }
        
        public AutenticacionUsuarioRequest(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad) {
            this.clsSeguridad = clsSeguridad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticacionUsuarioResult;
        
        public AutenticacionUsuarioResponse() {
        }
        
        public AutenticacionUsuarioResponse(string AutenticacionUsuarioResult) {
            this.AutenticacionUsuarioResult = AutenticacionUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsConsultaRadicado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wsConsultaRadicadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long txtCodigoRadicado;
        
        public wsConsultaRadicadoRequest() {
        }
        
        public wsConsultaRadicadoRequest(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad, long txtCodigoRadicado) {
            this.clsSeguridad = clsSeguridad;
            this.txtCodigoRadicado = txtCodigoRadicado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsConsultaRadicadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wsConsultaRadicadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet wsConsultaRadicadoResult;
        
        public wsConsultaRadicadoResponse() {
        }
        
        public wsConsultaRadicadoResponse(System.Data.DataSet wsConsultaRadicadoResult) {
            this.wsConsultaRadicadoResult = wsConsultaRadicadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaRadicadoWsSoapChannel : WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaRadicadoWsSoapClient : System.ServiceModel.ClientBase<WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap>, WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap {
        
        public ConsultaRadicadoWsSoapClient() {
        }
        
        public ConsultaRadicadoWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaRadicadoWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRadicadoWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRadicadoWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap.AutenticacionUsuario(WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest request) {
            return base.Channel.AutenticacionUsuario(request);
        }
        
        public string AutenticacionUsuario(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad) {
            WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest inValue = new WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest();
            inValue.clsSeguridad = clsSeguridad;
            WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse retVal = ((WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap)(this)).AutenticacionUsuario(inValue);
            return retVal.AutenticacionUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse> WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap.AutenticacionUsuarioAsync(WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest request) {
            return base.Channel.AutenticacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.AutenticacionUsuarioResponse> AutenticacionUsuarioAsync(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad) {
            WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest inValue = new WebServiceDatos.Web.wsServicios.AutenticacionUsuarioRequest();
            inValue.clsSeguridad = clsSeguridad;
            return ((WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap)(this)).AutenticacionUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap.wsConsultaRadicado(WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest request) {
            return base.Channel.wsConsultaRadicado(request);
        }
        
        public System.Data.DataSet wsConsultaRadicado(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad, long txtCodigoRadicado) {
            WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest inValue = new WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest();
            inValue.clsSeguridad = clsSeguridad;
            inValue.txtCodigoRadicado = txtCodigoRadicado;
            WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse retVal = ((WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap)(this)).wsConsultaRadicado(inValue);
            return retVal.wsConsultaRadicadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse> WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap.wsConsultaRadicadoAsync(WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest request) {
            return base.Channel.wsConsultaRadicadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDatos.Web.wsServicios.wsConsultaRadicadoResponse> wsConsultaRadicadoAsync(WebServiceDatos.Web.wsServicios.clsSeguridad clsSeguridad, long txtCodigoRadicado) {
            WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest inValue = new WebServiceDatos.Web.wsServicios.wsConsultaRadicadoRequest();
            inValue.clsSeguridad = clsSeguridad;
            inValue.txtCodigoRadicado = txtCodigoRadicado;
            return ((WebServiceDatos.Web.wsServicios.ConsultaRadicadoWsSoap)(this)).wsConsultaRadicadoAsync(inValue);
        }
    }
}
