//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServiceDatos.Web.NuevoDespachoWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NuevoDespacho_WsSoap", Namespace="http://tempuri.org/")]
    public partial class NuevoDespacho_Ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wsNuevoDespachoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NuevoDespacho_Ws() {
            this.Url = global::WebServiceDatos.Web.Properties.Settings.Default.WebServiceDatos_Web_wsNuevoDespacho_NuevoDespacho_Ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wsNuevoDespachoCompletedEventHandler wsNuevoDespachoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsNuevoDespacho", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsNuevoDespacho(long CodigoRadicado, string Descripcion, string Destino, string FechaDespacho) {
            object[] results = this.Invoke("wsNuevoDespacho", new object[] {
                        CodigoRadicado,
                        Descripcion,
                        Destino,
                        FechaDespacho});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsNuevoDespachoAsync(long CodigoRadicado, string Descripcion, string Destino, string FechaDespacho) {
            this.wsNuevoDespachoAsync(CodigoRadicado, Descripcion, Destino, FechaDespacho, null);
        }
        
        /// <remarks/>
        public void wsNuevoDespachoAsync(long CodigoRadicado, string Descripcion, string Destino, string FechaDespacho, object userState) {
            if ((this.wsNuevoDespachoOperationCompleted == null)) {
                this.wsNuevoDespachoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsNuevoDespachoOperationCompleted);
            }
            this.InvokeAsync("wsNuevoDespacho", new object[] {
                        CodigoRadicado,
                        Descripcion,
                        Destino,
                        FechaDespacho}, this.wsNuevoDespachoOperationCompleted, userState);
        }
        
        private void OnwsNuevoDespachoOperationCompleted(object arg) {
            if ((this.wsNuevoDespachoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsNuevoDespachoCompleted(this, new wsNuevoDespachoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void wsNuevoDespachoCompletedEventHandler(object sender, wsNuevoDespachoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsNuevoDespachoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsNuevoDespachoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591